- name: testing the variables
  hosts: localhost
  vars_prompt:
    - name: a
      prompt: enter a values
    - name: b
      prompt: enter the b value
  tasks:
  - name: printing the valies 
    ansible.builtin.debug:
      msg: "this will only wheen the two values areeuql"
    when: not a>b