- name: testing the variables
  hosts: localhost
  vars_prompt:
    - name: name
      prompt: please enter you name 
      private: false
    - name: age 
      prompt: please enter your age 
      private: true
  tasks:
  - name: displaying the multiple variables
    ansible.builtin.debug:
      msg: "my name is {{name}} and and my age is {{age}}"

 