- name: uing the error hanling conditions 
  hosts: node1
  tasks:
  - name: tagging the tasks
    become: yes 
    ansible.builtin.yum:
      name: nginx
      state: installed
    tags:
      - install 
      - installed
  - name: remving the nginx 
    become: yes
    ansible.builtin.yum:
      name: nginx 
      state: absent 
    tags: 
      - remove 
