- name: testing the variables
  hosts: localhost
  vars:
    details:
      - 1
      - 2
      - 3
      - 4
      - 5
      
   
  tasks:
  - name: variables prpcess
    ansible.builtin.debug:
      msg: " length of my list{{details | length}} and the first element is {{details | first }} and last element {{details | last}} and selecting the even elements {{details | select('even')}} and the odd the elements are {{details | select('odd')}}"
   