- name: testing the variables
  hosts: localhost
  vars:
    list1: [1,2,3,4,5]
    list2: [4,5,6,7,8]
  tasks:
  - name: combining the lsits
    ansible.builtin.set_fact:
      combined : {{combined | union(list1,list2)}}
  - name: displying the lsits 
    ansible.builtin.debug:
      msg: "this is the combined list{{combined}}"
   