- name: uing the error hanling conditions 
  hosts: node1
  tasks:
  - name: getting the file commnad
    ansible.builtin.command: /home/centod/mohan.txt
      register: result
  - name: the getting the name
    ansible.builtin.debug:
      msg: 'this is the output {{result}}'
