- name: testing the variables
  hosts: localhost
  vars:
    list1: [1, 2, 3, 4, 5]
    list2: [4, 5, 6, 7, 8]
    combined: []
  tasks:
    - name: combining the lists
      ansible.builtin.set_fact:
        combined: "{{ combined | union(list1, list2) }}"
    - name: displaying the lists
      ansible.builtin.debug:
        msg: "This is the combined list: {{ combined }}"
