- name: testing the variables
  hosts: localhost
  vars_files:
    - mohan.yml
  tasks:
  - name: displaying the multiple variables
    ansible.builtin.debug:
      msg: "my name is {{name}} and my age is {{age}} and my salary is {{salary}}"

 