- name: testing the variables
  hosts: localhost
  tasks:
  - name: getting the variables from the command line
    annsible.builtin.debug:
      msg: "the variable from the command line is {{name}}"
  