- name: testing the variables
  hosts: localhost
  vars_prompt:
    - name: a
      prompt: enter a values
    - name: b
      prompt: enter the b value
  tasks:
  - name: printing the valies 
    ansible.builtin.debug:
      msg: " installling theansible"
    when: a=="ansible" and b=="mohan"
    
      