- name: basic looping example
  hosts: localhost
  vars:
    fruits:
      name: mohan
      age: 25
      add: ganagavaram
  tasks:
  - name: print the message
    ansible.builtin.debug:
      msg: "the fruint{{item.key }} and {{item.value}}"
    with_items: "{{fruits | dict2items}}"

     