- name: testing the variables
  hosts: localhost
  vars:
    names:
      - mohan
      - vijay
      - chiru
  tasks:
  - name: variables prpcess
    ansible.builtin.debug:
      msg: "these are the friends{{item}}"
    with_items: "{{names}}"
    
  