- name: uing the error hanling conditions 
  hosts: node1
  tasks:
  - name: dispzying the ansible built in facts 
    ansible.builtin.debug:
      msg: " the ansible hostname {{ansible_hostname}}
            the ip addresss {{ansible_default_ipv4.address}} and os family is {{ansible_os_family}}"
 