- name: basic looping example
  hosts: localhost
  vars:
    fruits:
      - apple
      - banana
      - orange
  tasks:
  - name: print the message
    ansible.builtin.debug:
      msg: "the fruint{{item}}"
    with_items: "{{fruits | dict2items}}"

     