- name: testing the variables
  hosts: localhost
  vars:
    address:
      name: mohan
      age: 24
      per: ganagavram
  tasks:
    - name: combining the lists
      ansible.builtin.debug:
        msg: "{{item}}"
      loop: "{{address}}"