- name: testing the variables
  hosts: localhost
  vars_prompt:
    - name: name
      prompt: please enter your name 


  tasks:
  - name: displaying the multiple variables
    ansible.builtin.debug:
      msg: "your sting is converted into the upper case{{name}}"
  - name: stroting the variables into the list
    ansible.builtin.set_fact:
      values: "{{name | split(' ')}}"
  - name: printing the variables 
    ansible.builtin.debug:
      msg: "the each value is {{item}}"
    loop -
    {{values}}