- name: basic looping example
  hosts: localhost
  vars:
    name:
      - mohan
      - chiru
      - vijay
    age: 
      - 25
      - 26
      - 27
    
  tasks:
  - name: print the message
    ansible.builtin.debug:
      msg: "the fruint{{item.0 }} and {{item.1}}"
    with_together: 
      - "{{name}}"
      - "{{age}}"
     

