- name: basic looping example
  hosts: localhost
  vars:
    address:
      name: mohan
        age: 25
        address: gangavaram
      name: vijay
        age: 25
        address: palamaner
  tasks:
  - name: print the message
    ansible.builtin.debug:
      msg: "the fruint{{item.key }} and {{item.value}}"
    with_dict: "{{address}}"
     