- name: testing the variables
  hosts: localhost
  vars_files:
    - mohan.yaml
  tasks:
  - name: displaying the multiple variables
    ansible.builtin.debug:
      msg: "this is the mohan
            there is nothin you can do "

 