- name: uing the error hanling conditions 
  hosts: node1
  tasks:
  - name: printing the file contents
    ansible.builtin.command: cat mohan.txt
      register: output
  - name: priting the output
    ansible.builtin.debug:
      msg: "{{output}}"
