- name: basic looping example
  hosts: localhost
  vars:
    address:
      mohan:
        age: 25
        address: gangavaram
      vijay:
        age: 25
        address: palamaner
  tasks:
    - name: print the message
      ansible.builtin.debug:
        msg: "the fruit {{ item.key }} and {{ item.value.age }} years old, living in {{ item.value.address }}"
      with_dict: "{{ address }}"
